name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Self test
        id: selftest
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_WAKATIME }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "test/README.md"

      - name: Check outputs and modified files
        run: |
          cat test/README.md
