
name: Update README

on:
  push:
    branches:
        - main
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: msg087/public@main
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_WAKATIME }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_WAKATIME }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: msg087
          commit_user_email: 123316262+msg087@users.noreply.github.com
          commit_author: msg087