name: Update README
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"
jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Self test
        id: selftest
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_WAKATIME }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "test/README.md"
      - uses: msg087/public@main
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_WAKATIME }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"
      - name: Update Last Updated timestamp
        run: |
          sed -i "s/<!--LAST_UPDATED_TIMESTAMP-->/_Last Updated: $(date -u +"%Y-%m-%d %H:%M:%S")/" README.md
      - name: Check outputs and modified files
        run: |
          cat test/README.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README.md