
name: Update README

on:
  push:
    branches:
        - main
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Self test
        id: selftest
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_WAKATIME }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "test/README.md"

      - uses: msg087/public@main
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_WAKATIME }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - name: Check outputs and modified files
        run: |
          cat test/README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README.md
