name: Update README
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"
jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update Last Updated timestamp
        run: |
          sed -i "s/<!--LAST_UPDATED_TIMESTAMP-->/Last Updated: $(TZ=America/New_York date +"%Y-%m-%d %H:%M:%S EST")/" templates/README.md.tpl
      - uses: msg087/public@main
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_WAKATIME }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"
      - name: Check outputs and modified files
        run: |
          cat README.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README.md