name: Update README
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_README:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: msg087/public@main
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_WAKATIME }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"
      - name:  Check the template and Update Last Updated timestamp
        run: |
          echo "Get Updated Image"
          IMAGE_URL="<figure><embed src="https://wakatime.com/share/@msg087/abee4bda-6fcb-42a3-8f89-94cb929d9173.svg"></embed></figure>"
          curl -o img/waka_time.svg $IMAGE_URL
          echo "updating date"
          echo $(TZ=America/New_York date +'%Y-%m-%d %H:%M:%S EST')
          sed "s|<--LAST_UPDATED_TIMESTAMP-->|$(TZ=America/New_York date +'%Y-%m-%d %H:%M:%S EST')|" templates/README.md.tpl > README.md
          echo *********** README  ***********
          cat README.md
      - name: Commit README
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md img/waka_time.png
          git commit -m "Update README and waka_time image"
          git push
